### PR TITLE
Categorise the redirect document type

### PR DESCRIPTION
**Pull request by cbaines**
As a finding, within the user journey document supertype.

### CODE REVIEW

**Comment by tijmenb** [comment]
What's the reasoning & context behind this?

**Comment by cbaines** [comment]
> What's the reasoning & context behind this?

I was using the user journey document supertype to look at what content there is on GOV.UK, and noticed that redirects were not excluded as part of the navigation. Redirects to me are more about finding, rather than a thing you'd find, hence my suggestion to add it to the list.

**Comment by tijmenb** [comment]
This document type is going to be removed, so no need for this anymore.

**Comment by cbaines** [comment]
> This document type is going to be removed, so no need for this anymore.

This is the first I'm hearing about this. Is there any information about this available?

**Pull request closed without merging**
